### ISSUE TITLE
Reactotron inactive despite updated version and configuration

### ISSUE THREAD

**Issue by ldco2016** [infinitered/reactotron#1112]
I initially had problems with Reactotron not working until I upgraded the version and its corresponding configuration and then it worked.

```
 "reactotron-react-native": "3.5.0",
    "reactotron-redux": "3.1.0",

import {createStore, applyMiddleware, compose, combineReducers} from 'redux';

const appReducer = combineReducers({
  ...reducers,
});
const middleware = applyMiddleware(thunkMiddleware);
//react-native-debugger config
// eslint-disable-next-line no-underscore-dangle
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
// const store = Reactotron.createStore(appReducer, composeEnhancers(middleware));
const store = createStore(appReducer, composeEnhancers(middleware, Reactotron.createEnhancer()));

```
I am on React Native 0.59.9 at this point and Reactotron is no longer working.

With updated configuration and version numbers, I am not sure where to go from here.

**Comment by markrickert** [comment]
@ldco2016 I hope you've been able to solve your issues with Reactotron! If not, we've got an all new docs site with some updated documentation about integrating with redux: https://docs.infinite.red/reactotron/plugins/redux/

There's been a lot of updates since you opened this issue and if you haven't used Reactotron in a while, i'd say give it another try!
