### ISSUE TITLE
Reactotron does not support `BigInt()`

### ISSUE THREAD

**Issue by markrickert** [infinitered/reactotron#1436]
A community member raised an issue [in the reactotron channel](https://infiniteredcommunity.slack.com/archives/C42C5UKHV/p1707258028882889) that the library doesn't support `BigInt()`.

Indeed, it does not.

```tsx
<Button
  text="BigInt(0)"
  onPress={() => {
    console.log(BigInt(0))
  }}
/>
```

![image](https://github.com/infinitered/reactotron/assets/139261/56406853-b119-47ea-95f8-89468f050516)

**Comment by markrickert** [comment]
@mcreusot I just found [this thread](https://github.com/facebook/hermes/issues/510#issuecomment-1190033652) where it's stated that BigInt support was added to react native in 0.70.

I'll spin up an app with an older version and try and ship a permanent fix for this issue. Thanks for bringing it to my attention!

**Comment by hliejun** [comment]
I encountered this same issue as well while following the Reactotron Quick Start guide when shifting over from Flipper.

my package.json:
`
{
    ...
    "dependencies": {
        ...
        "react-native": 0.72.6,
        ...
    },
    "devDependencies": {
        ...
        "reactotron-react-native": "^5.1.4",
        "reactotron-redux": "^3.1.9",
        ...
    },
    ...
}
`

Since I was switching over from Flipper on a react-native project, I just decided to go with downgrading the dependencies.

Based on https://github.com/infinitered/reactotron/pull/1437/commits/846c8ca281b154cc05054dd3c57c0b30967257a0, as the BigInt reference in the `serialize.ts` of `reactotron-core-client` was added to address the JSON.stringify issue since `v2.9.0` of `reactotron-core-client`, I ended up referencing the older versions of Reactotron instead, so my package.json now looks like this:
`
{
    ...
    "dependencies": {
        ...
        "react-native": 0.72.6,
        ...
    },
    "devDependencies": {
        ...
        "reactotron-react-native": "5.0.5",
        "reactotron-redux": "3.1.7",
        "reactotron-core-client": "2.8.13",
        ...
    },
    ...
}
`
Since BigInt is undefined for react-native, I supposed it should be safe for me to stick with this version that is prior to the fix in v2.9.0. Perhaps a possible fix to address this in `reactotron-core-client` could be to add optional-chaining to the fix so that it only targets systems with BigInt?
`
BigInt?.prototype.toJSON = function() { return this.toString() }
`

**Comment by vasylnahuliak** [comment]
Still reproduce for React Native v0.72.4 (only for Android)

"reactotron-react-native": "^5.1.6",

**Comment by LouisMuriuki** [comment]
same issue on 
  "react-native": "0.71.11",

**Comment by c-goettert** [comment]
Inspired by @hliejun I came up with the following patch that solves the issue for me. However I have no Idea if it might break things (I didn't try to debug with android / reactotron yet):

[reactotron-core-client+2.9.3.patch](https://github.com/user-attachments/files/16426073/reactotron-core-client%2B2.9.3.patch)

**Comment by Harkindey** [comment]
@c-goettert please can you share the post where @hliejun suggested his solution, 🙏🏽.
