### ISSUE TITLE
`Maximum call stack size exceeded` on iOS 10

### ISSUE THREAD

**Issue by jgkim** [infinitered/reactotron#211]
When `reactotron` is used with [`react-native-router-flux`](https://github.com/aksonov/react-native-router-flux) connected to `redux` on iOS 10, it raises the `Maximum call stack size exceeded` error, calling `_hasBinary` of `socket.io` a lot.

It can be reproduced with the newly created [`ignite`](https://github.com/infinitered/ignite) project by changing `NavigationRouter.js` as the below.

``` javascript
import { Scene, Router as RNRFRouter } from 'react-native-router-flux'
import { connect } from 'react-redux'

[...]

const Router = connect()(RNRFRouter);
```

**Comment by skellock** [comment]
Totally struggling with that right now too.  I've temporarily turned of logging those commands until I get to the bottom of this.  💩

**Comment by jgkim** [comment]
It seems like this issue is somewhat related to socketio/socket.io#1665. If an object with cyclic object values is serialized, then the `Maximum call stack size exceeded` error is no longer raised but you can see some warnings saying `This synthetic event is reused for performance reasons.`.

**Comment by yinxin630** [comment]
Same issue as this. So how to solve it?

**Comment by skellock** [comment]
It's because a circular reference is being passed.  For example, you're trying to log something that's a react component (for example the `props` in `componentWillReceiveProps`) or react native router flux state.

The short term fix is to not log that (I know, not a fix).

The long term fix is for me to write (or find) something that detects circular references and uncircularfy them.

**Comment by tsemerad** [comment]
@skellock thanks. I upgraded my `reactotron-*` dependencies (like you suggested in #255), but now the app freezes on launch (at about the same point where the "Maximum call stack size exceeded" warnings were popping up on 1.5.1), taking no user input and requiring me to kill it. Unfortunately, there doesn't appear to be any error or warning message this time. I'm still using the Reactotron desktop client at version 1.5.0 - I'm assuming that's right since a new build wasn't included in the 1.5.2 release?

**Comment by skellock** [comment]
woah.  can you post that as a new issue?  if you can, maybe some relevant code to help track it down too.  thanks!

**Comment by skellock** [comment]
1.9 will put this stuff to rest finally.
