### ISSUE TITLE
normal yields are printed as unkown

### ISSUE THREAD

**Issue by andreiconstantinescu** [infinitered/reactotron#286]
Hey @skellock :) 

I have this usecase: 

A function returns a promise: `const getPromise = () => { ... }`

whenever in a `saga` i use `const result = yield getPromise()`, in Reactotron it is printed as `UNKNOWN` and the duration of it. It's annoying to see random `UNKNWON`s in the logs :(. 

How can I outcome this? :) 

Thanks!

LE: to be more accurate 

I have a 
```
const task = yield fork(someFunc) //this logs correctly in reactotron

const result = yield task.done //this logs UNKNOWN in reactotron
```

what i want to do is to launch a async req and know when it's done so that i can update the app state

**Comment by skellock** [comment]
Hmm...

Looks like it's not able to [detect the effect](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-redux-saga/src/get-effect-name.js#L17) properly.

In your top example:  I'd yield a `call` effect with a promise as opposed to the promise itself.

```js
yield call(getPromise())
```

In your bottom example, i'd use a `join` effect on the task.

```js
yield call(task)
```

Having said that, I'm very curious what happens when you yield things back to the `redux-saga` iterator that isn't an effect.  I mean, it should be fine, but I wondering if that's what triggering that 'unknown' case.

I will definitely play around around with this.

**Comment by andreiconstantinescu** [comment]
Awesome! Thanks for the tip with the `join`, worked like a charm, almost flawlessly. The only issue i encountered is that the duration doesn't seem to be right. My approraches were these: 

```
const [ a, b ] = yield [
    join(task1),
    join(task2)
  ]
```
<img width="545" alt="screen shot 2016-11-29 at 23 58 40" src="https://cloud.githubusercontent.com/assets/2974519/20734284/57b68a2e-b690-11e6-9230-7f5d6882654a.png">

```
  const a = yield join(task1)
  const b = yield join(task2)
```
<img width="539" alt="screen shot 2016-11-29 at 23 58 59" src="https://cloud.githubusercontent.com/assets/2974519/20734310/8a01e2c6-b690-11e6-8599-405b8b62d145.png">

where 
```
const task1 = yield fork(...)
const task2 = yield fork(...)
```

Any advice? :)

**Comment by skellock** [comment]
I prefer the first one.  :)  It reads well to me.

* kick off 2 independant tasks
* then wait for both to come back before i can continue

The timing for the top one makes sense to me too.  995ms until every task was done.  Task 1 was the slow guy that held everyone up.

The 2nd approach is:

* kick of 2 independant task
* now wait for the first one to come back... how long did i just wait?  634ms.
* ok good, now wait for the 2nd one... oh snap it's already done!?!?!, how long did i wait?  0ms.

Kinda wierd eh?

**Comment by skellock** [comment]
In 1.9, we will support both promises and unknown as a fallback.  🎉
