### ISSUE TITLE
Cannot find createSagaMonitor - "not a function"

### ISSUE THREAD

**Issue by jeffscottward** [infinitered/reactotron#305]
Per the instructions here.
https://github.com/reactotron/reactotron/blob/8eb86998133d18364b7e46dc804af6de9e778044/docs/plugin-redux-saga.md#step-2---plugin-to-redux-saga

I get the error.
![screen shot 2016-12-11 at 11 49 31 pm](https://cloud.githubusercontent.com/assets/1263486/21088373/8d1b8ad2-bffc-11e6-8284-17bbe8af568f.png)

Basic code is
```
    sagaMonitor = Reactotron.createSagaMonitor()
    sagaMiddleware = createSagaMiddleware({ sagaMonitor })
```

Reactotron is v 1.6 now. What is the status of this feature?

**Comment by skellock** [comment]
The status should be fine Jeff.

The `reactotron-redux-saga` plugin hasn't been loaded into Reactotron.  That's the plugin that makes that function available.  

Can we check a few things?

Do you have a ReactotronConfig.js file?  Is that being loaded before you load your Redux stuff?

If so, is your ReactotronConfig.js loaded via a `require` and your Redux stuff loaded via `import` from the same file?  Because imports get hoisted first despite your order in the file.

If that's all fine, are you loading the `reactotron-redux-saga` plugin, [as seen here](https://github.com/reactotron/reactotron/blob/master/packages/demo-react-native/App/Config/ReactotronConfig.js) on lines 4 and 23?

**Comment by jeffscottward** [comment]
> The status should be fine Jeff.
I don't understand what this means. I'm asking if the feature is soon to be implemented or not. 

> The reactotron-redux-saga plugin hasn't been loaded into Reactotron. That's the plugin that makes that function available.
So then this error is to be expected which is what I was asking in the first place. Basically, I followed everything perfectly and wanted to make sure that this error is not my fault.

> Do you have a ReactotronConfig.js file? Is that being loaded before you load your Redux stuff?
Yes

> Is your ReactotronConfig.js loaded via a require and your Redux stuff loaded via import from the same file
Everything is `import`s exactly as the docs show.

> If that's all fine, are you loading the reactotron-redux-saga plugin, as seen here on lines 4 and 23?
`.connect(sagaPlugin())` same thing.

Thanks for the debugging help but yea again, all I needed was this answer
`The reactotron-redux-saga plugin hasn't been loaded into Reactotron`
I found it weird the docs looked so great, and the UI so flush that it wasn't integrated.

When do you expect that it will be integrated?

**Comment by skellock** [comment]
`reactotron-redux-saga` is a plugin.  I don't automatically include this because not all people use that.  

One thing I'd be open to, however, is making a module which includes them all.  `reactotron-react-native-with-everything` or something.

Sorry for the confusion.

**Comment by hygkui** [comment]
@jeffscottward 
 I have the same issue, try to change this line

`sagaMonitor = Reactotron.createSagaMonitor()`

to

`sagaMonitor = Reactotron.createSagaMonitor`

**Comment by ahmad2smile** [comment]
In my case the problem was I wasn't using `.use` in config. 

Old setup:

`.useReactNative(sagaPlugin())`

Working Setup:

`.useReactNative()
	.use(sagaPlugin())`

**Comment by AleksandrChernyavenko** [comment]
When you make `release` version it cause error because you add `sagaPlugin` only if not a `__DEV__` mode

try next: 
```
  let sagaMiddleware;
  if (__DEV__) {
    const sagaMonitor = Reactotron.createSagaMonitor();
    sagaMiddleware = createSagaMiddleware({ sagaMonitor });
  } else {
    sagaMiddleware = createSagaMiddleware();
  }
```

**Comment by uusa35** [comment]
same issue here. none of the above worked with me

**Comment by rmevans9** [comment]
@uusa35 would you mind creating an issue with details around the code you are using please?

**Comment by cvng** [comment]
okay, this is the code that worked for me:

`import Reactotron from './ReactotronConfig'`

**Comment by marcelxsilva** [comment]
I have the same error, my code:

```
import React from 'react';
import { Provider } from "react-redux";
import './config/ReactotronConfig';
import store from './store'
```;

i did only:
```
import React from 'react';
import './config/ReactotronConfig';
import { Provider } from "react-redux";
import store from './store'
```;

**Comment by rodalcala** [comment]
> okay, this is the code that worked for me:
> 
> `import Reactotron from './ReactotronConfig'`

This did the trick for me as well but I'm not happy with it since I'm now importing it even in production.

This is the import method suggested in [the documentation](https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md):
`if(__DEV__) {
  import('./ReactotronConfig').then(() => console.log('Reactotron Configured'))
}`

But doesn't matter that's in the first line of the App.js, it will load after the store is configured and therefore not work.
Does anybody know why?
