### ISSUE TITLE
Error when running React Native Demo: (0,_reactotronReactNative.overlay) is not a function

### ISSUE THREAD

**Issue by lewisle** [infinitered/reactotron#328]
Hi,
I've got this error when running the demo on iPhone simulator. Not sure how to fix it. Could you please advise?

<img width="487" alt="screen shot 2017-02-01 at 10 17 04 am" src="https://cloud.githubusercontent.com/assets/929120/22494152/a43c5122-e867-11e6-85b1-0b346b446679.png">

**Comment by kevinvangelder** [comment]
Looks like your Reactotron NPM module is out of date. Give `npm update` and `react-native start --reset-cache` a try.

**Comment by lewisle** [comment]
Thank Kevin. I've tried but, unfortunately, it did not work. The error is still there. By the way, it seems that my npm is already up-to-date.

**Comment by skellock** [comment]
Ya...

Here's the awkward thing with React Native 3rd party plugins....

They don't support symlinks.  There's been several attempts at getting it working on React Native, but it doesn't seem to do the trick.

So in our repo, we have to do a few tricks.  From the root of this project, here's what I've been doing to make this work:

```sh
npm run bootstrap
cd packages/demo-react-native
./copy-internal-deps.sh
```

This will get you a "healthy" demo environment.  Now just launch react native as normal.

Sorry it's a pain in the butt.  I get frustrated that I have to do this too.

(btw your error was because it's getting the latest off of npm and I've yet to release the overlay stuff)

**Comment by kevinvangelder** [comment]
Oh, my bad, I thought this was an issue on Ignite. #fail
