### ISSUE TITLE
Change ¯\_(ツ)_/¯ to `null` in output

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/reactotron#331]
Per #327, sometimes the ¯\_(ツ)_/¯  is confusing in output, especially to newbies. Let's just output `null` or `undefined` as expected. Maybe put the `¯\_(ツ)_/¯ ` after them?

```
null ¯\_(ツ)_/¯ 
undefined ¯\_(ツ)_/¯ 
```

**Comment by skellock** [comment]
I can't just do it because null and undefined dont serialize in json.  I lose that bit of identification when i jump the wire.  Thats why I print Mr. Shruggy.  I really dont know which one it is.

I'll consider this though when I address the performance issues with serialization.  I might have to switch to a new format which will preserve that.

I agree its not clear though.  Was just keeping things light and fun.

**Comment by skellock** [comment]
Also if you have any ideas for the serialization issues, that'd be welcome!  Cuz we could do this client side too.

**Comment by kevinvangelder** [comment]
Couldn't you just send a string `"null/undefined"` with Mr. Shruggy?

**Comment by skellock** [comment]
yep.  and the act of inspecting the hierarchy of object is part of the performance problem i'm having... i'm doing that to detect circular dependencies and name functions.

https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-client/src/scrub.js#L22

Works great for small objects.  

Dies horribly on larger.

Since the communication part is kind of a private API, I'd be open to drastic changes such as MsgPack or whatever the cool kids are using nowadays for serialization.

**Comment by jamonholmgren** [comment]
Once things settle down on the Ignite / <new project> end of things, I can help with this.
