### ISSUE TITLE
React Native - AsyncStorage UI

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#354]
https://facebook.github.io/react-native/docs/asyncstorage.html

I don't see any type of event listeners so it may not be a "live" view but it would be neat for it to pull all the keys/values and display them in Reactotron. Might be useful for debugging when AsyncStorage is in use.

**Comment by rmevans9** [comment]
With a quick test an option for keeping a "live view" of the async storage I found that you could "overwrite" the async storage methods.

```
import { AsyncStorage } from 'react-native';

const originalSetItem = AsyncStorage.setItem;
AsyncStorage.setItem = (key, value, callback) => {
    // Do something to ship either this key to Reactotron or the entire async storage
    originalSetItem(key, value, callback);
}
```

**Comment by skellock** [comment]
I'm up for putting this on Tab 4... I'd like to have a sub-nav switch between React Native tools.

We could piggyback it onto `reactotron-react-native`?

Let me know what I can do to help @rmevans9.  

I can do the UI part if you'd like.  I've been considering redoing the UI internals because it's a mess. I always feel guilty when someone goes in there.  :)

**Comment by rmevans9** [comment]
That would work for me. I will look to land a PR in the next day or two to wire up shipping this information out of the socket connection.

**Comment by skellock** [comment]
I think is good for now.  Let's see what we want when it gets used in action.

#366
