### ISSUE TITLE
global.BlobBuilder issue

### ISSUE THREAD

**Issue by marciobueno1** [infinitered/reactotron#358]
![screen shot 2017-03-10 at 10 12 15](https://cloud.githubusercontent.com/assets/9195580/23797074/db332a98-057c-11e7-9cc7-db25f105abd7.png)

I am trying to use the Reactotron.createStore, but it gives me this error...

I was able to make this work if I put all redux, createStore, middleware, saga, ... in the same file.

But, I am not getting what configuration I am done wrong when I split this on different files.

I create a repository to reproduce this problem: [marciobueno1/Reactotron-Navigation-Redux-Example](https://github.com/marciobueno1/Reactotron-Navigation-Redux-Example)

Everything works (without reactotron connection) if in file store.js I use the createStore from the 'redux' package.

**Comment by skellock** [comment]
Thanks for the repro.  Makes it nice to track these things down.

Two things:

There's a bug in Reactotron that I'll fix up.  But you need a 3rd parameter to be a identity function if you're not using middleware.  Change [that line](https://github.com/marciobueno1/Reactotron-Navigation-Redux-Example/blob/master/store.js#L7) to:

```js
const store = Reactotron.createStore(reducer, {}, sorry => sorry)
```

I'll fix that up.

The other issue is:  for React Native projects, everything you need (out of the box at least) is in the `babel-preset-react-native`.  So that means, remove your extra stuff in `.babelrc` (just leave the `react-native` preset.  Also, remove those extra babel things in your node_modules.  Don't need 'em anymore.

Lemme know if that gets you up & running.   Don't forget to clear the React Native packager cache. `npm start -- --reset-cache`.

Feel free to re-open if it doesn't.

**Comment by marciobueno1** [comment]
Thanks for taking your time to having a look on this, now it is working...

I pushed the changes to my repository removing all babel and eslint related things...

Later, I will try to put some of the eslint config to see if it still works...

**Comment by mradziwon** [comment]
I have the same problem and solution with 3rd parameter is not working.

**Comment by marciobueno1** [comment]
@mradziwon, did you check your package.json to see if there is another babel package that can cause the problem?

**Comment by mradziwon** [comment]
My bad. It was connected to babel settings.

**Comment by Dictory** [comment]
Have same issue. I reload my mac and get that error.

**Comment by skellock** [comment]
Probably best to open a new issue.  Try to rule out the `--reset-cache` issue and that you're not running the chrome debugger.

**Comment by Dictory** [comment]
Ok that was long road to fix this issue, short long story:
Unlink all packages, uninstall pods, upgrade react-native by [rn-diff](https://github.com/ncuillery/rn-diff), check major changes in other rn-packages, use [new pods](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies) for rn > 0.47, link packages and install pods.

use [kin](https://github.com/Karumi/Kin) for lint xcode project
