### ISSUE TITLE
Show a preview in AsyncStorage

### ISSUE THREAD

**Issue by ferrannp** [infinitered/reactotron#391]
Hi! Awesome lib, thanks for it. 

Right now `AsyncStorage` is showing like:

<img width="563" alt="screen shot 2017-04-15 at 01 50 25" src="https://cloud.githubusercontent.com/assets/774577/25058825/f3faf2c8-217d-11e7-9f58-8e57128e24e7.png">

I think it would be optimal if we show a preview (like Redux action names). We could show the name of the method plus arguments (if it has). Like:

```
ASYNC STORAGE: setItem(App@SomeKey)
ASYNC STORAGE: removeItem(App@SomeKey)
ASYNC STORAGE: clear()
...
```

I was checking into the code and I think it would need some tweaks here [AsyncStorageValuesCommand.js#L46](https://github.com/infinitered/reactotron/blob/597fe49fc460dffeb0109856aeb36a740fe0a6e9/packages/reactotron-app/App/Commands/AsyncStorageValuesCommand.js#L46). I'd try to PR but not sure how to build the `.app` without signing it? Actually I never created an .app for desktop Mac.

Ah, then we would need something like:

```
reactotron.send('asyncStorage.values.change', { preview: `${method}(${arg})`, value: valuesToSend } );
```

WDYT? 😄

**Comment by skellock** [comment]
I like it!

You won't need to sign it.  I can do that.  If you can just make it run with `yarn start` and send a screenshot, you've got my vote!

**Comment by ferrannp** [comment]
All right, I had some trouble running `demo-react-native` app locally but it looks like I got over it with the following steps:

- Add `socket-io-client` as dep for `demo-react-native`
- I bumped `haul@0.5.0`
- With `haul` the app runs correctly. However, to see the messages in the Electron app I need to have the debugger open

I am gonna give the PR a go for the `AsyncStorage`.

**Comment by skellock** [comment]
That `socket-io-client` dependency should come in with `reactotron-react-native`.  The reason why it's not is because this is a lerna repo.  

This relies on symlinks.  

And symlinks don't work well in React Native.

Which is why I'm so excited to get haul setup here.  =)

Sorry for the bumps.  I'd love to get to the spot where:

* `yarn run welcome` sets up your complete dev environment
* `yarn run dev` sets up watchers to rebuild any child lib as well as haul
* editing a file anywhere will just do the right thing... in any project.

**Comment by ferrannp** [comment]
Done #392!
