### ISSUE TITLE
Integrating w/ IDEs (in place of the GUI APP)

### ISSUE THREAD

**Issue by orther** [infinitered/reactotron#455]
Hello, I've been using Reactotron quite a bit lately and I appreciate the extra insight it has provided as I massage my sagas into perfection. So to begin I'd like to say, "Thank you!"

And now onto it... I've been recently considering the idea of writing an emacs package to connect directly to the Reactotron server which would in theory allow me to enjoy Reactotron features from the comfort of Emacs. From a high level view this looks straightforward (like most software when your only 30 minutes in). Basically 'Emacs connects to the Reactotron server using websockets, and the life is good! All plugins work and there are no problem. After some less than thorough review of code it does appears the project is organized in a way that could support what I am describing but before I dig any further into researching feasibility and planning I'd like to ask a few things:
1. Is supporting/promoting integrating 3rd-party clients outside the officials CLI & GUI App something you even want to encourage? 
1. Are there any obviously technical reasons you don't think this is a compelling area to focus effort (on my part)?
1. Is there anyone else that has already started on this journey that this you suggest I look into?
1. And finally if it does sound interesting to you, is there any documentation or information you suggest I delve into first to help understand the bigger picture and specific implementation details to help me begin to organize my my thoughts and planning?

Either way thanks for Reactotron and for taking the time to read this issue.

**Comment by skellock** [comment]
Oh man.  That's great to hear.  I use this software everyday, so I take it a bit for granted, but it's awesome to hear it's helpful from others.

So... yes is the answer to "would you encourage it?"

In fact, I was kicking around the idea of a VS Code integration now that they're heading in the direction of custom ui (they're still not there 100% yet).

Currently everything you need is in the `reactotron-core-server`, but a few caveats you should know of:

* It currently uses `socket.io`.  And soon it won't.  It will use straight up websockets.  I just haven't had time to finish that stage up just yet.
* The protocol is kinda not documented well. I haven't kept it up to date because there's never really been a 3rd party reason (until now!).  To get a sense of what i have, [read this section](https://github.com/infinitered/reactotron/tree/master/packages/reactotron-core-client#messages).

If you use slack, join us at http://community.infinite.red in the #reactotron channel for some realtime support, or github issues is totally fine too if you want async conversations.

**Comment by skellock** [comment]
Going to close. Would really love to see something like this in play. It’s a fair amount of work. =)
