### ISSUE TITLE
Improve Reactotron API

### ISSUE THREAD

**Issue by yordis** [infinitered/reactotron#628]
I will copy-paste what I currently have implemented that I would like to have on Reactotron itself.

PS: Please ignore `configure` function because it is relative to my environment

```javascript
import { NativeModules } from "react-native";
import ReactotronInstance from "reactotron-react-native";
import { reactotronRedux } from "reactotron-redux";
import sagaPlugin from "reactotron-redux-saga";
import url from "url";

export type ReactotronType = any;

const noop = () => undefined;

const configure = (appName: string, tron: ReactotronType) => {
  const { hostname } = url.parse(NativeModules.SourceCode.scriptURL);

  tron
    .configure({ name: appName, host: hostname })
    .useReactNative({
      asyncStorage: true,
      editor: true,
      errors: true,
      networking: true,
      overlay: true,
    })
    .use(reactotronRedux())
    .use(sagaPlugin())
    .connect();

  tron.clear();
};

export class Reactotron {
  public static createReactotron(args: {
    appName: string;
    enabled?: boolean;
  }) {
    const {
      appName,
      enabled = false,
    } = args;

    if (enabled) {
      configure(appName, ReactotronInstance);
    }

    return {
      withReactotron(withCallback: (tron: ReactotronType) => any, withoutCallback = noop) {
        return enabled ? withCallback(ReactotronInstance) : withoutCallback();
      },
    };
  };
}
```

## Allow me to specify the environment

Notice that I pass the attribute `enabled` which let the instance to know if I will be using Reactotron or not.

I am not quite sure how Reactotron does the internals but if the function` withReactotron` gets implemented I would like to have some flag where I let Reactotron knows if I want to enable or not `implicit`, I wouldn't rely on `__ENV__` (maybe for default value) or anything like that because then I can't control it with a single environment file.

## Add Reactotron function that uses a callback

Rather than `if statements` (based on Ignite generator where there is multiple strategies for it) we rely on the fact the callback will never be executed and as you can notice we take the `reactotron instances as a parameter` so this way the scope of that functions do not need to worry about it at all.

All your code would become `withReactotron( tron => tron.log("nice) )`.

## Thoughts

- If you really worry about removing extra bites of your application, it is always easier to remove from the JS AST, because we could just wipe out the entire function declaration without worries, it think should be simpler than finding if statements that look for `.tron` or any other thing that people could use and then becomes problematic for the core to maintain.

- If the people do not want to ship Reactotron to production because it cost some bites, then we could think about some dynamic loader I guess?! Basically the idea is that you wouldn't need a complex Reactotron instance because you will call a single function that will do nothing anyway.

cc: @skellock @jamonholmgren

**Comment by skellock** [comment]
Hey, thx for the write up.  This is something I've thought a lot about too.  And your technique looks good, I do something similar too. 

### Dev vs Prod

Dev vs prod is something I've been flip-flopping on for years now.  

Here's my latest opinion as of 4 days ago:

![image](https://user-images.githubusercontent.com/68273/37912236-0a98dd3e-30e0-11e8-89fc-56d624f3e2e3.png)

(private repo or I would have just linked it!)

### Interface

I'd like to keep the interface available globally.  I find it incredibly convenient to just add a line anywhere (including `node_modules` libs) with `console.tron.log`.

I know that's insanely ghetto, and that's why I don't actually install it like that out of the box.

I do this nowadays:

```ts

import Tron from "reactotron-react-native"
import { RootStore } from "../../models/root-store"
import { onSnapshot } from "mobx-state-tree"
import { ReactotronConfig, DEFAULT_REACTOTRON_CONFIG } from "./reactotron-config"
import { mst } from "reactotron-mst"

// Teach TypeScript about the bad things we want to do.
declare global {
  interface Console {
    /**
     * Hey, it's Reactotron if we're in dev, and no-ops if we're in prod.
     */
    tron: typeof Tron
  }
}

/** Do Nothing. */
const noop = () => undefined

// in dev, we attach Reactotron, in prod we attach a interface-compatible mock.
if (__DEV__) {
  console.tron = Tron // attach reactotron to `console.tron`
} else {
  // attach a mock so if things sneaky by our __DEV__ guards, we won't crash.
  console.tron = {
    configure: noop,
    connect: noop,
    use: noop,
    useReactNative: noop,
    clear: noop,
    log: noop,
    logImportant: noop,
    display: noop,
    error: noop,
  }
}
```

I still guard calls with `__DEV__` like this:

```ts
__DEV__ && console.tron.log(stuff)
```

But if I forget, the `noop`s will ensure something doesn't crash.


### Compile-time Removal

I went that route with [babel-plugin-ignite-ignore-reactotron](https://github.com/infinitered/babel-plugin-ignite-ignore-reactotron).  That's something that can strip out Reactotron from prod builds if you want.

I'm on the fence with this. It just feels too risky.  I've seen a crash once on a non-ignite project because I transformed something into oblivion and left a syntax error in it's place.

It's too fragile for my liking, but you may enjoy it.  It's useful though.

### Now What?

This doesn't belong in Reactotron tho, but in the app you're building (or boilerplate). 

That's my take on it.

I'd like to support all of these:

* 👍 leave it in for prod testing?
* 👍 strip it out at compile time?
* 👍 `__DEV__` guards?

Devs use this library more adhoc and freestyle rather a library that's typically built into their app.

Also,

Thanks again.  I sincerely love hearing how other people set it up and work with it.

**Comment by yordis** [comment]
@skellock add the `TronMock` object in Reactotron 😄 I didn't know I would mock that many functions so that is why I preferred to pass as a parameter and forget about it.

**Comment by rmevans9** [comment]
I have no idea if this would work with TypeScript but this harnesses the fact that `metro` optimizes out things in a `__DEV__` check:

```
if (__DEV__) {
  const reactotronAll = require("reactotron-react-native");

  const Reactotron = ReactotronAll.default;

  Reactotron.configure()
    .use(ReactotronAll.useReactNative())
    .connect();

  console.tron = Reactotron;
} else {
  const noop = () => undefined;

  console.tron = {
    configure: noop,
    connect: noop,
    use: noop,
    useReactNative: noop,
    clear: noop,
    log: noop,
    logImportant: noop,
    display: noop,
    error: noop
  };
}
```

**Comment by jamonholmgren** [comment]
I like the idea of exporting a `TronMock` object that stubs out the public API.

```typescript
import Tron from "reactotron-react-native"
import { RootStore } from "../../models/root-store"
import { onSnapshot } from "mobx-state-tree"
import { ReactotronConfig, DEFAULT_REACTOTRON_CONFIG } from "./reactotron-config"
import { mst } from "reactotron-mst"

// Teach TypeScript about the bad things we want to do.
declare global {
  interface Console {
    /**
     * Hey, it's Reactotron if we're in dev, and no-ops if we're in prod.
     */
    tron: typeof Tron
  }
}

console.tron = __DEV__ ? Tron : Tron.TronMock
```
