### ISSUE TITLE
Debug messages when we cannot connect

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#63]
I heard here (https://github.com/infinitered/ignite/issues/261) that some setups have an issue connecting from the client to the server.

We should add some kind of debugging tips (even if it's just console.log) that help understand exactly where the problem lies.

**Comment by mmzoo** [comment]
This would help me debug why the reactotron CLI works fine, but nothing shows up in the Reactotron macOS app.

**Comment by skellock** [comment]
Agreed.  

I can try to help though!

Usually it has to do with `host`.  Are you using Android?  Emulator or device?

**Comment by mmzoo** [comment]
ios Simulator. I suppose it's running here:

```
http://0.0.0.0:8081/index.ios.bundle?platform=ios&dev=true&hot=true
```
but default for reactotron is `localhost:8080`, isn't it? I'm confused as to where to configure Reactotron.app.

**Comment by skellock** [comment]
Reactotron.app listens on port 9090 on interface 0.0.0.0.  The defaults for the sim should work.  (that is: `Reactotron.configure().connect()`).

The app currently has no configuration, though.  The client just connects to localhost from the iOS sim, and all *should* be well.

What does your `ReactotronConfig.js` look like (or whenever you set that up)?

**Comment by mmzoo** [comment]
Thank you for pointing me into the right direction and for your time. Turns out our app is many months behind when it comes to how reactotron is required and configured. I didn't pay attention to that fact because the CLI was working out of the box even with the current setup.

Either way, debugging is a good thing to have ;)

**Comment by skellock** [comment]
Do you get an error with the store?  Or does nothing redux seem to work?

**Comment by mmzoo** [comment]
The store works just fine in general, I can see it in the Chrome JS console. The reactotron setup is virtually identical to the one you use in the ignite app.

I suspect it has to do with outdated packages, such as using react `0.31.0` and react `15.2.1`.

**Comment by imod** [comment]
this would still be very useful, my setup used to work just fine. Then I updated the Reactotron App and since it does not work anymore. (Even after downgrading the app)

**Comment by skellock** [comment]
Check that your libs and app are on the same stream.  If your libs are `1.x`, the app needs to be `1.x`. If the libs are `2.x`, so too must be the app.

**Comment by imod** [comment]
actually just found the issue per accident - I had another (zombie) process listening on port `9090`, killing it fixed the issue. Still I think it would be very helpful to give some hints about connection problems during start. I only found out about port `9090` because I found some issues where you mentioned this specific port.

**Comment by skellock** [comment]
Not at the moment, but it totally needs to be a thing.

**Comment by skellock** [comment]
Closing in favour of #792
