### ISSUE TITLE
RFC - Easier Custom Commands

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#640]
Custom commands are quite useful, but it's not the nicest interface.

It'd be great to have Reactotron take care of this.

### Currently

```ts
Reactotron.use( tron => {
  return {
    onCommand: async cmd => {
      if (cmd.type !== "custom") return
      switch (cmd.payload) {
         case "something":
           // do something
         case "something-else":
           // do something else
      }
    }
  }
})
```

What makes this awkward (in addition to the boilerplate) is that this happens early in your app startup.  You need to add Reactotron plugins (via `.use`) before you connect.  So you might not have everything at that time.

Perhaps, and build that plugin into the core.

Then you can subscribe to custom events wherever you want in your app.

### Proposed

```ts
console.tron.onCustomCommand("something", async (payload: string) => {
  await AsyncStorage.clear()
  console.tron.log("async storage cleared.")
})
```

Another example is you can effortlessly put it in strange places like React components.

```ts
class MyCompy extends React.Component<{}, {}> {
  cleanupAisle7: any

  componentDidMount() {
    this.cleanupAisle7 = console.tron.onCustomCommand("something", () => {
      this.setState({ data: [] })
    })
  }

  componentWillUnmount() {
    this.cleanupAisle7 && this.cleanupAisle7()
  }

  render () {
    // stuff
  }
}
```

**Comment by rmevans9** [comment]
I think this is a good approach. I wonder if we could take this a step further and have all the "registered" commands show up in the reactotron UI automagically. That is assuming that was not already on your mind when thinking about this.

Also - in the future you could possibly take an (optional) parameter that sets the possible input value to a type so you could pass a command with some sort of parameter. An example would be the currently implemented storybook switcher command - you send in `storybook:true` or `storybook:false`. In this case the Reactotron UI would let you select the "storybook" command then present you with a checkbox or something of that nature so that you could send in the parameter as well.

**Comment by skellock** [comment]
I was not thinking of that at all.

That's a fantastic idea.

**Comment by rmevans9** [comment]
I was bored tonight after cleaning up the connection filtering UI so I did a thing.

https://github.com/infinitered/reactotron/pull/641

**Comment by skellock** [comment]
This is now shipping (the code part from above is... not the bonus ui stuff -- but that's good enough for now!).
