### ISSUE TITLE
Can't connect my device to reactotron using `expo`

### ISSUE THREAD

**Issue by itaied246** [infinitered/reactotron#695]
I'm using `ignite andross` boilerplate.

`ReactotronConfig.js`:

```js
import Config from '../Config/DebugConfig'
import Immutable from 'seamless-immutable'
import Reactotron from 'reactotron-react-native'
import { reactotronRedux as reduxPlugin } from 'reactotron-redux'
import sagaPlugin from 'reactotron-redux-saga'
import { NativeModules } from 'react-native'
import url from 'url'

if (Config.useReactotron) {
  const {hostname} = url.parse(NativeModules.SourceCode.scriptURL)

  console.log('using reactotron at ' + hostname)
  // https://github.com/infinitered/reactotron for more options!
  Reactotron
    .configure({name: 'Ignite App', host: hostname, port: 19001})
    .useReactNative()
    .use(reduxPlugin({onRestore: Immutable}))
    .use(sagaPlugin())
    .connect()

  // Let's clear Reactotron on every time we load the app
  Reactotron.clear()

  Reactotron.log('hello from reactotron!')

  // Totally hacky, but this allows you to not both importing reactotron-react-native
  // on every file.  This is just DEV mode, so no big deal.
  console.tron = Reactotron
}
```

I do see the log `using react native at <my-host-name>`,
but opening up `Reactotron`, I can't see any activity in the timeline.

What am I missing?

**Comment by rmevans9** [comment]
Can you confirm the versions of both the NPM package and Reactotron app that you are using?

**Comment by itaied246** [comment]
`Reactotron` v1.6.8
`npm` 5.6.0

**Comment by rmevans9** [comment]
The issue is that you are using alpha versions of the npm packages but the stable version of the reactotron app which we switched out how they communicate so that won't work. What you have to do is head to the releases page here in GitHub and download the latest 2.0.0 beta version of the app (currently beta 5) and then try. While you are at it you should update `reactotron-react-native` `reactotron-redux` and `reactotron-redux-saga` to beta 5 as well as beta 3 had a pretty nasty little but that made state subscriptions not work.

**Comment by itaied246** [comment]
Thanks!
works
