### ISSUE TITLE
Feature Request: Make datasets copyable

### ISSUE THREAD

**Issue by CorinneKelly** [infinitered/reactotron#720]
When debugging API calls it would be helpful to be able to copy and paste the logged responses (arrays, objects and all other data types) so that the frontend team can easily show the backend team exactly what is being returned. At the moment our work around is to open as many datasets (using the click down arrow) as are viewable on a laptop screen and send a screenshot to the other devs we are trying to communicate with. However, this is not efficient because it then requires someone to type out the data in order to perform lookups in the database or to use the response in any way.

It would be ideal if there was an easy way to copy and paste ALL the data thats being displayed by reactotron.

**Comment by rmevans9** [comment]
Hello @CorinneKelly 

I think I am following what you are looking for and, assuming I am understanding correctly, you are in luck! That feature exists today (and has for a long while). See the circled arrow on the API Response item? Click that and your clipboard is magically filled with response goodness. On a side note if you send a payload to the server via the body of the request there will be an arrow pointing in the other direction too which copies out your request body.

![screen shot 2018-07-02 at 7 06 25 pm](https://user-images.githubusercontent.com/14151327/42190456-3733cca8-7e2b-11e8-9272-3de88f7fdec9.png)

Going to close this for now since I believe this is what you are looking for? If not please feel free to open it back up and let me know where I misunderstood.

Thanks!
