### ISSUE TITLE
Add Debugger

### ISSUE THREAD

**Issue by morenoh149** [infinitered/reactotron#728]
This is an amazing tool. The fact that the devtools cannot show networks requests made me search for this.

It'd be great if I could debug sourcecode with reactotron as well. Using the `debugger` statement.

**Comment by skellock** [comment]
ya... agreed. this is something not on the radar for this project.  reactotron was born out of my frustrations with chrome debugging.  id rather see us push for deeper integration & inspection features like performance tracking and resource usage.

if jsc is where your app runs, thats where it should be debugged... otherwise you run into issues like networking not working or js features working when they shouldn’t... all sorts of fun stuff...

**Comment by morenoh149** [comment]
gotcha
