### ISSUE TITLE
Reactotron.log(this) crashes my application

### ISSUE THREAD

**Issue by xMaarf** [infinitered/reactotron#780]
I created my project with Ignite Andross boilerplate.
And everytime I try to console.tron.log(this) or Reactotron.log(this) my application crashes with no error message or any log.
I'm not supposed to try to console.log this? 
I actually have no idea what's going on, it's the first time that I'm using Reactotron.

My react-native version is 0.55.1.
Developing in Windows.

**Comment by skellock** [comment]
Depends on the value of `this`.  My guess is that you’re attempting to log something like a React component. Perhaps in `render()` or `componentWillMount` situation?

This is problematic due to some pretty nifty circular dependencies within that object.

Reactotron is an out-of-process app, so we have to serialize to get from your app to the Reactotron app.  To do that we use `JSON.serialize`.  Which is circular dependency hostile.  I’ve got some code to prevent circular refs, but can’t seem to make it work for React components.

You can log their props, state, and many other objects just fine, but not everything.

Can you share the code here that’s crashing?

**Comment by rmevans9** [comment]
Closing for now. @xMaarf if you are still running into this please let us know here.
