### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by JulienMalige** [infinitered/reactotron#816]
I installed the app via direct download. I manage updates by going on GitHub to check if there is a new release. 

How do you generally manage updates of Reactotron ? By using the brew install ? Did you already think about adding a "check for updates" on start ? Maybe I could make this PR :)

**Comment by rmevans9** [comment]
👋 Hello @JulienMalige!

We considered adding a auto update to the electron app. Then we decided we wanted to just dump electron completely and go a different route. Work for V3 is underway which switches to a web based application (read: no electron) that you install directly to your project as a devDependency. As such we will not be adding a auto updater to the app as you will handle updates via your package.json/lock file like any other dependency.

For me for v2 I just grab the latest from the releases page when it becomes available. Obviously this will stop once v3 lands.

Closing this for now since we are changing how this works in the upcoming work we have underway. If you need anything else just let us know!

Thanks
