### ISSUE TITLE
The actions log history is limited 

### ISSUE THREAD

**Issue by conor909** [infinitered/reactotron#819]
I find the actions log too limited as I have some automatic actions firing on every page update.  I need to be able to scroll right through the history since the beginning of app startup.  Or mute / hide certain actions so I can pick out the ones that are relevant.

**Comment by skellock** [comment]
We have a buffer of [500 messages](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Lib/commands.js#L5).  

Although there is filtering & searching functions in the app, they don't prevent messages from filling up that buffer; they merely prevent viewing.

If you're using `reactotron-redux` or `reactotron-mst`, there are ways to filter out actions from ever jumping the wire.  You might want to use these if there are some actions you know will never need be updated.

We don't have an unlimited buffer though since, at the moment, it's a very chatty protocol.

**Comment by rmevans9** [comment]
Closing in favor of https://github.com/infinitered/reactotron/issues/922 which is seemingly heading toward a solution to this issue.
