### ISSUE TITLE
Docs for milliseconds in top left of Timeline Item?

### ISSUE THREAD

**Issue by tannera** [infinitered/reactotron#867]
I've looked around the docs and release notes for information on what exactly the time duration in ms represents in the top left of each timeline item. Can anyone clarify this? It's not the duration of the request since the number is different from the response duration(ms) underneath. 

<img width="548" alt="screenshot 2018-10-19 at 10 03 11" src="https://user-images.githubusercontent.com/4791996/47205515-6ea22a80-d386-11e8-80b2-e14bbadbebff.png">

**Comment by rmevans9** [comment]
This was added a while back and I need to understand it better myself. We really need to get the docs updated for this.

**Comment by markrickert** [comment]
@tannera The little red `+n ms` at the top of each timeline entry is the elapsed time between when those entries entered the timeline. 

So in your example screenshot, that API response took 254ms but the response was logged out to the reactotron timeline 92ms after the previous log (whatever it was that came through the websockets connection).

These numbers are meant to be *general* so that you can diagnose timing issues in your code but should not be relied on to be absolutely accurate due to the nature of how reactotron communicates with your app over a websockets connection.
